import test from 'node:test';
import assert from 'node:assert/strict';
import {FakegaleTrader,validateFakegale,mhiSeeds,rankMhis,MHI_PATTERNS} from '../vps-backend/automation/FakegaleTrader.js';
const start=1800000000;
function fixture(t){t.mock.timers.enable({apis:['Date'],now:start*1000});const calls=[];const session={activeMode:'demo',modeStates:{demo:{},real:{}},accountCurrency:'USD',balance:100,saveToFile:()=>true,syncToClients(){},connectDeriv(){},derivAPI:{connected:true,authorized:true,fetchCandleHistory:async()=>[],sendRequest:async req=>{calls.push(req);assert.ok(!req.buy&&!req.sell);if(req.proposal)return{proposal:{id:'quote',ask_price:req.amount,payout:req.amount*1.9,spot:100,spot_time:Date.now()/1000}};return{history:{times:[req.start+1],prices:[99]}}}}};const engine=new FakegaleTrader(session);engine.configure({enabled:true});engine.state.pending.push({id:'cycle',symbol:'R_100',strategy:'mhi_1_minority',direction:'CALL',stage:0,scheduled:start,profit:0,entries:0,selected:true,quote:null});return{engine,session,calls};}
test('Fakegale rejects execution flags and budgets smaller than all three stakes',()=>{assert.throws(()=>validateFakegale({execution:'live'}));assert.throws(()=>validateFakegale({stake:2,multiplier:3,cycleBudget:20}));assert.equal(validateFakegale({}).stake,1.5);});
test('all six MHI seeds use only the previous block final three closed candles',()=>{const c=[-180,-120,-60].map((delta,i)=>({epoch:start+delta,open:100,close:i?101:99}));const seeds=mhiSeeds(c,start+2);assert.equal(seeds.length,6);assert.equal(seeds[0].direction,'PUT');assert.equal(seeds[4].scheduled,start+120);assert.equal(mhiSeeds(c,start+25).length,0);assert.equal(mhiSeeds(c.slice(1),start).length,0);});
test('two virtual losses precede three simulated stakes; no balance mutation or purchase',async t=>{const {engine,session,calls}=fixture(t);await engine.tick();assert.equal(engine.state.trades.length,0);t.mock.timers.tick(65000);await engine.tick();assert.equal(engine.state.trades.length,0);t.mock.timers.tick(65000);await engine.tick();assert.equal(engine.state.pending[0].stage,2);assert.equal(engine.state.trades.length,0);for(let i=0;i<3;i++){t.mock.timers.tick(65000);await engine.tick();}assert.deepEqual(engine.state.trades.map(r=>r.stake),[1.5,4.5,13.5]);assert.equal(engine.state.cycles[0].profit,-19.5);assert.equal(session.balance,100);assert.equal(engine.state.pending.length,0);assert.equal(calls.filter(r=>r.proposal).length,5);});
test('a virtual win cancels the cycle before any simulated paid stage',async t=>{const {engine,session}=fixture(t);await engine.tick();session.derivAPI.sendRequest=async req=>({history:{times:[req.start+1],prices:[101]}});t.mock.timers.tick(65000);await engine.tick();assert.equal(engine.state.pending.length,0);assert.equal(engine.state.trades.length,0);assert.equal(engine.state.baseline[0].profit,1.5*1.9-1.5);});
test('pause settles an existing quote but cannot open another stage; state isolated by account',async t=>{const {engine,session,calls}=fixture(t);await engine.tick();engine.configure({enabled:false});t.mock.timers.tick(65000);await engine.tick();assert.equal(calls.filter(r=>r.proposal).length,1);assert.equal(engine.state.pending.length,0);session.activeMode='real';assert.equal(engine.state.config.enabled,false);assert.equal(engine.state.baseline.length,0);});
test('ranking requires twenty past initial outcomes and does not count gale recovery as an initial win',()=>{const s={};s['R_100:'+MHI_PATTERNS[0].id]=Array(19).fill(true);assert.equal(rankMhis(s,'R_100')[0].ready,false);s['R_100:'+MHI_PATTERNS[1].id]=Array(20).fill(true);assert.equal(rankMhis(s,'R_100')[0].id,MHI_PATTERNS[1].id);});
test('invalid exit data cannot manufacture virtual losses',async t=>{const {engine,session}=fixture(t);await engine.tick();session.derivAPI.sendRequest=async req=>({history:{times:[req.start+90],prices:[99]}});t.mock.timers.tick(65000);await engine.tick();assert.equal(engine.state.pending[0].stage,0);assert.equal(engine.state.baseline.length,0);});
