import test from 'node:test';
import assert from 'node:assert/strict';
import {FakegaleTrader,validateFakegale,streakSignal,FAKEGALE_VERSION} from '../vps-backend/automation/FakegaleTrader.js';
const start=1800000000;
const candle=(epoch,up=true)=>({epoch,open:100,close:up?101:99,high:102,low:98});
function fixture(t){t.mock.timers.enable({apis:['Date'],now:start*1000});const calls=[],candles=[candle(start-180,false),candle(start-120,true),candle(start-60,true)];const session={activeMode:'demo',modeStates:{demo:{},real:{}},balance:100,saveToFile:()=>true,syncToClients(){},connectDeriv(){},derivAPI:{connected:true,authorized:true,fetchCandleHistory:async()=>candles,sendRequest:async req=>{calls.push(req);assert.ok(!req.buy&&!req.sell);if(req.active_symbols)return{active_symbols:[{underlying_symbol:'R_100',pip_size:.01}]};if(req.proposal)return{proposal:{id:req.contract_type,ask_price:req.amount,payout:req.contract_type==='CALL'?1.88:1.9,spot:100,spot_time:Date.now()/1000}};if(req.count===100)return{history:{times:[req.start+1],prices:[100]}};return{history:{times:[req.start],prices:[101]}};}}};const engine=new FakegaleTrader(session);engine.configure({enabled:true,symbols:['R_100']});return{engine,session,calls};}

test('V3 rejects real execution and removed martingale parameters',()=>{assert.throws(()=>validateFakegale({execution:'live'}));assert.throws(()=>validateFakegale({multiplier:3}));assert.equal(validateFakegale({}).stake,1);});
test('streak detector uses only contiguous closed M1 candles and distinguishes depth',()=>{const two=[candle(start-180,false),candle(start-120,true),candle(start-60,true)],three=two.map(row=>({...row,open:100,close:101}));assert.deepEqual({...streakSignal(two,start+2),range:undefined},{depth:2,follow:'CALL',reverse:'PUT',key:start-60,range:undefined});assert.equal(streakSignal(three,start+2).depth,3);assert.equal(streakSignal(two,start+20),null);assert.equal(streakSignal(two.filter((_,i)=>i!==1),start+2),null);assert.equal(streakSignal([...two,candle(start+1,false)],start+2).depth,2);});
test('old V2 evidence is retained as archive while V3 starts paused and empty',()=>{const session={activeMode:'real',modeStates:{real:{fakegale:{version:'fakegale-v2.1',config:{enabled:true},trades:[{profit:-1}],baseline:[{profit:.8}],cycles:[{profit:-.2}]}}}};const engine=new FakegaleTrader(session),snapshot=engine.snapshot();assert.equal(snapshot.version,FAKEGALE_VERSION);assert.equal(snapshot.config.enabled,false);assert.equal(snapshot.trades.length,0);assert.deepEqual(snapshot.legacyV2.trades,{count:1,wins:0,net:-1});});
test('reversal and continuation share one future entry and exit without purchases',async t=>{const {engine,session,calls}=fixture(t);await engine.tick();assert.equal(engine.state.pending.length,1);assert.deepEqual(engine.state.pending[0].legs.map(leg=>leg.arm),['reverse_2','follow_2']);assert.equal(engine.state.trades.length,0);t.mock.timers.tick(5000);await engine.tick();assert.equal(engine.state.pending[0].entry,100);assert.equal(engine.state.trades.length,0);t.mock.timers.tick(65000);await engine.tick();const rows=engine.state.trades;assert.equal(rows.length,2);assert.equal(rows[0].entryEpoch,rows[1].entryEpoch);assert.equal(rows[0].exitEpoch,rows[1].exitEpoch);assert.deepEqual(rows.map(row=>row.profit),[-1,.88]);assert.equal(session.balance,100);assert.ok(calls.every(req=>!req.buy&&!req.sell));});
test('pause prevents new pairs while an existing pair is still settled',async t=>{const {engine}=fixture(t);await engine.tick();engine.configure({enabled:false});t.mock.timers.tick(5000);await engine.tick();t.mock.timers.tick(65000);await engine.tick();assert.equal(engine.state.trades.length,2);assert.equal(engine.state.pending.length,0);});
test('daily loss and drawdown limits block only the affected alternative wallet',t=>{const {engine}=fixture(t),ledger=engine.ledger('reverse_2');ledger.day=new Date().toISOString().slice(0,10);ledger.dayLoss=3;assert.equal(engine.reserve('reverse_2',1),false);assert.equal(engine.reserve('follow_2',1),true);});
test('missing future entry is excluded and releases both hypothetical reserves',async t=>{const {engine,session}=fixture(t);await engine.tick();session.derivAPI.sendRequest=async req=>req.count===100?{history:{times:[],prices:[]}}:{active_symbols:[]};t.mock.timers.tick(35000);engine.lastPoll=0;await engine.tick();assert.equal(engine.state.pending.length,0);assert.equal(engine.state.trades.length,0);assert.equal(engine.ledger('reverse_2').reserved,0);assert.equal(engine.ledger('follow_2').reserved,0);});
