import React, {useEffect,useState} from 'react';
import {Play,Pause,Save,Download} from 'lucide-react';
import {FAKEGALE_DEFAULTS,MHI_PATTERNS,validateFakegale} from '../../vps-backend/automation/FakegaleTrader.js';
import {ASSETS} from '../../vps-backend/automation/signals.js';
import {summarize} from '../../vps-backend/automation/research.js';
const usd=n=>Number(n||0).toLocaleString('en-US',{style:'currency',currency:'USD'});
const percent=n=>n==null?'—':n.toFixed(1)+'%';
export default function FakegalePanel({state,available,pending,onConfigure}){
 const [draft,setDraft]=useState({...FAKEGALE_DEFAULTS}),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[asset,setAsset]=useState('all'),[pattern,setPattern]=useState('all');
 useEffect(()=>{if(state?.config&&!dirty)setDraft(state.config)},[state?.config,dirty]);
 const update=(key,value)=>{setDirty(true);setDraft(d=>({...d,[key]:value}));};
 const apply=patch=>{try{validateFakegale(patch,state?.config||FAKEGALE_DEFAULTS);onConfigure(patch);setDirty(false);setError('');}catch(e){setError(e.message);}};
 const filter=t=>(asset==='all'||t.symbol===asset)&&(pattern==='all'||pattern==='leader'?pattern!=='leader'||t.selected:t.strategy===pattern);
 const rows=(state?.trades||[]).filter(filter).sort((a,b)=>a.timestamp-b.timestamp),first=rows.filter(t=>t.stage===2),baseline=(state?.baseline||[]).filter(filter);
 const m=summarize(rows),initial=summarize(first),base=summarize(baseline),values=[0,...m.curve.map(p=>p.equity)],low=Math.min(...values),high=Math.max(...values),span=high-low||1;
 const exportData=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:state.version,simulationOnly:true,config:state.config,asset,pattern,trades:rows,baseline,virtuals:(state.virtuals||[]).filter(filter),cycles:(state.cycles||[]).filter(filter),rankings:state.rankings},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='fakegale-v2-simulacao.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="fakegale-panel">
 <div className="workspace-heading"><div><span className="workspace-eyebrow">PESQUISA CONTÍNUA / 100% SIMULADO</span><h1>Trader Contínuo Fakegale<span>.</span></h1><p>V2 · duas perdas virtuais antes da entrada simulada. MHI 1, 2 e 3, minoria e maioria.</p></div><span className="workspace-status">{state?.status||'Aguardando VPS compatível'}</span></div>
 <section className="aut-card"><h2>Uma modalidade independente</h2><p>Virtual inicial → virtual G1 → entrada simulada → G1 simulado → G2 simulado. Uma vitória virtual descarta a sequência; uma vitória após o filtro encerra o ciclo. A direção é mantida durante todo o ciclo. Nenhuma etapa compra contratos ou altera o saldo da conta.</p>
 <div className="aut-form"><label>Entrada simulada (USD)<input type="number" min="0.35" step="0.01" value={draft.stake} onChange={e=>update('stake',Number(e.target.value))}/></label><label>Multiplicador simulado<input type="number" min="1" max="5" step="0.1" value={draft.multiplier} onChange={e=>update('multiplier',Number(e.target.value))}/></label><label>Teto por ciclo (USD)<input type="number" value={draft.cycleBudget} onChange={e=>update('cycleBudget',Number(e.target.value))}/></label><label>Payout mínimo líquido<input type="number" min="0.1" max="2" step="0.05" value={draft.minPayout} onChange={e=>update('minPayout',Number(e.target.value))}/></label></div>
 <fieldset><legend>Ativos acompanhados</legend><div className="aut-checks">{ASSETS.map(s=><label key={s}><input type="checkbox" checked={draft.symbols.includes(s)} onChange={e=>update('symbols',e.target.checked?[...draft.symbols,s]:draft.symbols.filter(x=>x!==s))}/>{s}</label>)}</div></fieldset>
 <p>Entradas previstas: {[0,1,2].map(g=>usd(Math.round(draft.stake*draft.multiplier**g*100)/100)).join(' → ')}. Cada padrão é um experimento separado. O teto se aplica a um ciclo, não à soma de todos os experimentos.</p>
 <div className="aut-actions"><button className="workspace-button" disabled={!available||pending||!dirty||!!state?.pending?.length} onClick={()=>apply(draft)}><Save size={15}/>Salvar parâmetros simulados</button><button className="workspace-button workspace-button-primary" disabled={!available||pending} onClick={()=>apply(state?.config?.enabled?{enabled:false}:{...(dirty?draft:{}),enabled:true})}>{state?.config?.enabled?<Pause size={15}/>:<Play size={15}/>} {state?.config?.enabled?'Pausar Fakegale V2':'Iniciar Fakegale V2 simulado'}</button></div>{error&&<p role="alert">{error}</p>}
 <p>Pausar impede novas etapas e mantém a apuração das etapas já abertas. Alterações de parâmetros exigem que não existam simulações pendentes.</p></section>
 <section className="aut-card"><h2>MHI acompanhado por ativo</h2><p>Ranking descritivo dos últimos 100 resultados iniciais de cada padrão, sem gales. O líder só é escolhido após 20 resultados e usa uma estimativa conservadora de acerto. A escolha fica fixada antes da primeira etapa do bloco. Não é probabilidade comprovada nem aprovação para operar.</p><div className="aut-table"><table><thead><tr><th>Ativo</th><th>Padrão</th><th>Amostra</th><th>Acerto inicial</th><th>Estado</th></tr></thead><tbody>{Object.entries(state?.rankings||{}).flatMap(([symbol,list])=>list.map((r,i)=><tr key={symbol+r.id}><td>{symbol}</td><td>{r.name}</td><td>{r.count}/100</td><td>{percent(r.winRate)}</td><td>{!r.ready?'Aquecendo':i===0?'Líder para próximo bloco':'Em comparação'}</td></tr>))}</tbody></table></div><p>Na inicialização não há histórico inventado: o aquecimento pode levar cerca de 100 minutos ou mais. Todos os padrões são simulados durante esse período.</p></section>
 <section className="aut-card"><h2>Resultados da simulação</h2><div className="aut-filters"><label>Ativo da análise<select value={asset} onChange={e=>setAsset(e.target.value)}><option value="all">Todos</option>{ASSETS.map(s=><option key={s}>{s}</option>)}</select></label><label>Padrão da análise<select value={pattern} onChange={e=>setPattern(e.target.value)}><option value="all">Todos os experimentos</option><option value="leader">Somente líder pré-selecionado</option>{MHI_PATTERNS.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><button className="workspace-button" disabled={!state} onClick={exportData}><Download size={15}/>Exportar Fakegale V2</button></div>
 <div className="aut-metrics"><article><span>Resultado simulado</span><strong>{usd(m.net)}</strong><small>{m.count} entradas após o filtro, incluindo gales</small></article><article><span>Acerto após duas perdas</span><strong>{percent(initial.winRate)}</strong><small>{initial.count} primeiras entradas após o filtro · sem gales</small></article><article><span>Acerto inicial sem filtro</span><strong>{percent(base.winRate)}</strong><small>{base.count} etapas iniciais virtuais · amostra diferente</small></article><article><span>Queda acumulada</span><strong>{usd(m.drawdown)}</strong><small>{state?.pending?.length||0} sequências em andamento</small></article></div>
 <div className="aut-equity"><div><b>Curva acumulada simulada</b><span>{usd(low)} a {usd(high)}</span></div>{rows.length?<svg viewBox="0 0 800 190" role="img" aria-label={`Curva Fakegale V2: ${rows.length} entradas simuladas`}><polyline fill="none" stroke={m.net<0?'#fb8b9e':'#a7dac9'} strokeWidth="2.5" points={values.map((v,i)=>`${20+i/(values.length-1)*760},${160-(v-low)/span*135}`).join(' ')}/></svg>:<p>Aguardando duas perdas virtuais e a primeira entrada simulada liquidada nesta seleção.</p>}</div><p>Exibe até 2.000 entradas e 2.000 etapas iniciais carregadas. A soma de experimentos sobrepostos não representa uma carteira executável. Simulação usa spot e payout da proposta; não reproduz a liquidação da corretora. Taxas com amostras diferentes não comprovam causalidade.</p></section>
 <section className="aut-card"><h2>Sequências em andamento</h2><div className="aut-table"><table><thead><tr><th>Ativo</th><th>MHI</th><th>Etapa</th><th>Estado</th><th>Selecionado</th></tr></thead><tbody>{(state?.pending||[]).map(p=><tr key={p.id}><td>{p.symbol}</td><td>{p.strategy}</td><td>{p.stage<2?`Virtual ${p.stage+1}`:`Simulada G${p.stage-2}`}</td><td>{p.phase}</td><td>{p.selected?'Sim':'Experimento'}</td></tr>)}</tbody></table></div>{!state?.pending?.length&&<p>Aguardando próximo bloco de cinco minutos dos MHIs.</p>}</section>
 <section className="aut-card"><h2>Últimas entradas simuladas</h2><div className="aut-table"><table><thead><tr><th>Data</th><th>Ativo / MHI</th><th>Nível</th><th>Entrada</th><th>Resultado</th></tr></thead><tbody>{rows.slice(-40).reverse().map(t=><tr key={t.id}><td>{new Date(t.timestamp).toLocaleString()}</td><td>{t.symbol} / {t.strategy}</td><td>G{t.stage-2}</td><td>{usd(t.stake)}</td><td>{usd(t.profit)}</td></tr>)}</tbody></table></div>{(state?.events||[]).slice(-5).reverse().map((e,i)=><p key={i}>{new Date(e.time).toLocaleTimeString()} · {e.symbol} · {e.message}</p>)}</section>
 </section>;
}
