import React,{useEffect,useState} from 'react';
import {Activity,ArrowDownUp,Download,Pause,Play,Save,ShieldCheck} from 'lucide-react';
import {FAKEGALE_ARMS,FAKEGALE_DEFAULTS,validateFakegale} from '../../vps-backend/automation/FakegaleTrader.js';
import {ASSETS} from '../../vps-backend/automation/signals.js';
import {summarize} from '../../vps-backend/automation/research.js';
const usd=value=>Number(value||0).toLocaleString('en-US',{style:'currency',currency:'USD'}),percent=value=>value==null?'—':`${value.toFixed(1)}%`;
const colors={reverse_2:'#72ddc1',follow_2:'#7da8ff',reverse_3:'#d6a6ff',follow_3:'#ffb66e'};
function Countdown(){const [now,setNow]=useState(Date.now());useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[]);const seconds=60-Math.floor(now/1000)%60;return <strong>{`00:${String(seconds%60).padStart(2,'0')}`}</strong>;}
function Curves({rows}){const series=FAKEGALE_ARMS.map(arm=>{let total=0;return{arm,points:rows.filter(row=>row.arm===arm.id).sort((a,b)=>a.timestamp-b.timestamp).map(row=>({time:row.timestamp,value:total+=row.profit}))};}),points=series.flatMap(item=>item.points);if(!points.length)return <p>A curva começa após o primeiro par encerrado.</p>;const low=Math.min(0,...points.map(p=>p.value)),high=Math.max(0,...points.map(p=>p.value)),start=Math.min(...points.map(p=>p.time)),end=Math.max(start+1,...points.map(p=>p.time));return <div className="aut-equity"><div><b>Curvas alternativas · não somar</b><span>{usd(low)} a {usd(high)}</span></div><svg viewBox="0 0 800 210" role="img" aria-label="Comparação Fakegale Regime V3">{series.map(item=>item.points.length?<polyline key={item.arm.id} fill="none" stroke={colors[item.arm.id]} strokeWidth="2.2" points={item.points.map(p=>`${20+(p.time-start)/(end-start)*760},${180-(p.value-low)/(high-low||1)*150}`).join(' ')}/>:null)}</svg></div>;}
export default function FakegalePanel({state,available,pending,onConfigure}){
 const [draft,setDraft]=useState({...FAKEGALE_DEFAULTS}),[dirty,setDirty]=useState(false),[error,setError]=useState(''),[asset,setAsset]=useState('all'),[depth,setDepth]=useState('all');
 useEffect(()=>{if(state?.config&&!dirty)setDraft(state.config);},[state?.config,dirty]);
 const update=(key,value)=>{setDirty(true);setDraft(current=>({...current,[key]:value}));},apply=patch=>{try{validateFakegale(patch,state?.config||FAKEGALE_DEFAULTS);onConfigure(patch);setDirty(false);setError('');}catch(reason){setError(reason.message);}};
 const rows=(state?.trades||[]).filter(row=>(asset==='all'||row.symbol===asset)&&(depth==='all'||row.depth===Number(depth))),exportData=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({...state,exportedAt:Date.now(),scope:{asset,depth}},null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='fakegale-regime-v3.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <section className="fakegale-panel fakegale-v3">
  <div className="workspace-heading"><div><span className="workspace-eyebrow">EXPERIMENTO CONTÍNUO · PARES CAUSAIS</span><h1>Fakegale Regime V3<span>.</span></h1><p>Reversão contra continuação depois de sequências reais de duas ou três velas M1.</p></div><span className="workspace-status">{state?.status||'Aguardando VPS compatível'}</span></div>
  <section className="fake-v3-hero"><div><span className="workspace-eyebrow"><ArrowDownUp size={14}/> NOVA HIPÓTESE</span><h2>Depois da sequência, o preço reverte ou continua?</h2><p>O robô espera duas ou três velas fechadas da mesma cor e abre duas alternativas simuladas no próximo tick. Ambas compartilham entrada, vencimento e preço de saída. Isso mede diretamente qual comportamento paga melhor, sem gale e sem aumentar a stake.</p><div className="fake-v3-flow"><span>2–3 velas iguais</span><i>→</i><span>Entrada futura comum</span><i>→</i><span>Reversão × continuação</span><i>→</i><span>Apuração em 1 min</span></div></div><div className="fake-v3-scan"><Activity/><span>Próxima janela M1</span><Countdown/><small>Entrada depende da sequência e do payout</small></div></section>
  <section className="aut-card"><div className="fake-v3-title"><div><span className="workspace-eyebrow">CONTROLE DO TESTE</span><h2>Coleta simulada independente</h2></div><span className="simulation-seal">SEM COMPRAS<br/>SEM MARTINGALE</span></div><div className="aut-form"><label>Stake indicativa por alternativa<input type="number" min="0.35" max="20" step="0.01" value={draft.stake} onChange={event=>update('stake',Number(event.target.value))}/></label><label>Payout líquido mínimo<input type="number" min="0.1" max="2" step="0.05" value={draft.minPayout} onChange={event=>update('minPayout',Number(event.target.value))}/></label></div><fieldset><legend>Índices acompanhados</legend><div className="aut-checks">{ASSETS.map(symbol=><label key={symbol}><input type="checkbox" checked={draft.symbols.includes(symbol)} onChange={event=>update('symbols',event.target.checked?[...draft.symbols,symbol]:draft.symbols.filter(item=>item!==symbol))}/>{symbol}</label>)}</div></fieldset><div className="aut-actions"><button className="workspace-button" disabled={!available||pending||!dirty||!!state?.pending?.length} onClick={()=>apply(draft)}><Save size={15}/>Salvar parâmetros</button><button className="workspace-button workspace-button-primary" disabled={!available||pending} onClick={()=>apply(state?.config?.enabled?{enabled:false}:{...(dirty?draft:{}),enabled:true})}>{state?.config?.enabled?<Pause size={15}/>:<Play size={15}/>} {state?.config?.enabled?'Pausar V3':'Iniciar V3 simulado'}</button></div>{error&&<p role="alert">{error}</p>}<p className="evidence-note">Carteiras separadas de US$100; perda bruta diária de US$3 e drawdown máximo de US$15 por alternativa. A coleta de pesquisa continua sem alocação quando uma carteira atinge o limite.</p></section>
  <section className="aut-card"><div className="fake-v3-title"><div><span className="workspace-eyebrow">PLACAR PROSPECTIVO</span><h2>Quatro hipóteses, dois testes pareados</h2></div><div className="aut-filters"><label>Ativo<select aria-label="Ativo Fakegale V3" value={asset} onChange={event=>setAsset(event.target.value)}><option value="all">Todos</option>{ASSETS.map(symbol=><option key={symbol}>{symbol}</option>)}</select></label><label>Sequência<select aria-label="Sequência Fakegale V3" value={depth} onChange={event=>setDepth(event.target.value)}><option value="all">2 e 3 velas</option><option value="2">2 velas</option><option value="3">3 velas</option></select></label><button className="workspace-button" disabled={!state} onClick={exportData}><Download size={15}/>Exportar</button></div></div><div className="fake-v3-arms">{FAKEGALE_ARMS.map(arm=>{const metric=summarize(rows.filter(row=>row.arm===arm.id)),ledger=state?.ledgers?.[arm.id];return <article key={arm.id} style={{'--arm-color':colors[arm.id]}}><span>{arm.mode==='reverse'?'REVERTER':'CONTINUAR'} · {arm.depth} VELAS</span><strong className={metric.net<0?'negative':'positive'}>{usd(metric.net)}</strong><small>{metric.count} pares · {percent(metric.winRate)}</small><div><ShieldCheck size={13}/> carteira {usd(ledger?.bank??100)} · queda {usd(ledger?.drawdown)}</div></article>;})}</div><Curves rows={rows}/><p className="evidence-note">Cada par representa alternativas mutuamente exclusivas. Somar as curvas criaria uma carteira impossível. Compare lucro por entrada, payout, drawdown e estabilidade por ativo e profundidade.</p></section>
  <section className="aut-card"><h2>Pares em apuração</h2>{(state?.pending||[]).length?<div className="aut-table"><table><thead><tr><th>Ativo</th><th>Sequência</th><th>Entrada</th><th>Alternativas</th><th>Estado</th></tr></thead><tbody>{state.pending.map(position=><tr key={position.id}><td>{position.symbol}</td><td>{position.depth} velas</td><td>{position.entry==null?'Próximo tick':position.entry}</td><td>Reversão × continuação</td><td>{position.blocked||'Aguardando apuração'}</td></tr>)}</tbody></table></div>:<p>Aguardando uma sequência válida no fechamento M1.</p>}{(state?.events||[]).slice(-5).reverse().map(event=><p key={`${event.time}-${event.symbol}`}>{new Date(event.time).toLocaleTimeString()} · {event.symbol||'sistema'} · {event.message}</p>)}</section>
  {state?.legacyV2&&<section className="aut-card fake-v3-archive"><span className="workspace-eyebrow">ARQUIVO CONGELADO</span><h2>Fakegale V2 encerrado</h2><p>Os dados anteriores permanecem exportáveis e não entram no V3.</p><div className="aut-metrics"><article><span>Entradas V2</span><strong>{state.legacyV2.trades.count}</strong><small>{usd(state.legacyV2.trades.net)}</small></article><article><span>Etapas iniciais</span><strong>{state.legacyV2.baseline.count}</strong><small>{usd(state.legacyV2.baseline.net)}</small></article><article><span>Ciclos retidos</span><strong>{state.legacyV2.cycles.count}</strong><small>{usd(state.legacyV2.cycles.net)}</small></article></div></section>}
 </section>;
}
