import React, { useMemo, useState } from 'react';
import { ArrowUpRight, Download, FlaskConical, SlidersHorizontal } from 'lucide-react';
import { summarize } from '../../vps-backend/automation/research.js';
import { auditRows, auditGroups, bankReplay, auditCsv, strategyName, tradeTime } from './auditMetrics.js';
import './StrategyAudit.css';
const money = n => Number(n || 0).toLocaleString('en-US', { style: 'currency', currency: 'USD' });
const pct = n => n == null ? '—' : `${n.toFixed(1)}%`;
function Breakdown({ title, rows }) {
  return <section className="audit-panel"><h2>{title}</h2><div className="audit-table"><table><thead><tr><th>Nome</th><th>Contratos</th><th>Acerto</th><th>Resultado</th></tr></thead><tbody>{rows.map(r => <tr key={r.name}><td>{r.name}</td><td>{r.count}</td><td>{pct(r.winRate)}</td><td className={r.net < 0 ? 'audit-loss' : 'audit-gain'}>{money(r.net)}</td></tr>)}</tbody></table>{!rows.length && <p className="audit-empty">Sem dados para comparar.</p>}</div></section>;
}
export default function StrategyAudit({ trades = [], continuous, isDemo, connected, onResearch }) {
  const [source, setSource] = useState('timeline'), [period, setPeriod] = useState('7');
  const [strategy, setStrategy] = useState('all'), [symbol, setSymbol] = useState('all'), [bank, setBank] = useState('100');
  const raw = source === 'timeline' ? trades : (continuous?.trades || []).filter(t => t.execution === source);
  const valid = useMemo(() => auditRows(raw), [raw]);
  const since = period === 'all' ? 0 : Date.now() - Number(period) * 86400000;
  const rows = auditRows(valid, { since, strategy, symbol }), metrics = summarize(rows), replay = bankReplay(rows, Number(bank));
  const changeSource = value => { setSource(value); setStrategy('all'); setSymbol('all'); };
  const exportData = () => { const url = URL.createObjectURL(new Blob([auditCsv(rows)], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `astrobot-auditoria-${isDemo ? 'demo' : 'real'}-${source}.csv`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); };
  return <main className="strategy-audit">
    <header className="audit-heading"><div><span className="audit-eyebrow">ASTROBOT / EVIDÊNCIAS E PESQUISA</span><h1>Análise de Estratégias<span>.</span></h1><p>Entenda os resultados registrados antes de ajustar sua operação.</p></div><button className="audit-button" onClick={onResearch}><FlaskConical size={16} /> Pesquisa e replay <ArrowUpRight size={15} /></button></header>
    <div className="audit-context"><span>{isDemo ? 'CONTA DEMO' : 'CONTA REAL'}</span><p>{source === 'observe' ? 'Observação indicativa · resultados hipotéticos, sem compras.' : 'Contratos liquidados · resultado individual de cada entrada, incluindo gales.'} {!connected && 'VPS desconectada: últimos dados disponíveis.'}</p></div>
    <section className="audit-panel audit-filters" aria-label="Filtros da análise"><label>Origem<select aria-label="Origem" value={source} onChange={e => changeSource(e.target.value)}><option value="timeline">Agenda / manual</option><option value="live">Trader Contínuo · compras</option><option value="observe">Trader Contínuo · observação</option></select></label><label>Período<select aria-label="Período" value={period} onChange={e => setPeriod(e.target.value)}><option value="1">Últimas 24 horas</option><option value="7">Últimos 7 dias</option><option value="30">Últimos 30 dias</option><option value="all">Histórico carregado</option></select></label><label>Estratégia<select aria-label="Estratégia" value={strategy} onChange={e => setStrategy(e.target.value)}><option value="all">Todas</option>{[...new Set(valid.map(strategyName))].sort().map(s => <option key={s}>{s}</option>)}</select></label><label>Ativo<select aria-label="Ativo" value={symbol} onChange={e => setSymbol(e.target.value)}><option value="all">Todos</option>{[...new Set(valid.map(t => t.symbol).filter(Boolean))].sort().map(s => <option key={s}>{s}</option>)}</select></label><button className="audit-button" disabled={!rows.length} onClick={exportData}><Download size={15} /> Exportar CSV</button></section>
    <section className="audit-metrics" aria-label="Métricas da seleção">{[
      ['Resultado líquido', money(metrics.net), `${metrics.count} contratos válidos`, metrics.net < 0],
      ['Taxa de acerto', pct(metrics.winRate), `${metrics.wins} ganhos · ${metrics.losses} perdas · ${metrics.count-metrics.wins-metrics.losses} empates`],
      ['Fator de lucro', metrics.profitFactor == null ? '—' : metrics.profitFactor.toFixed(2), metrics.grossLoss ? 'Ganhos brutos / perdas brutas' : 'Indefinido sem perdas registradas'],
      ['Queda máxima', money(metrics.drawdown), `Maior sequência: ${metrics.maxLossRun} perdas`]
    ].map(([label,value,note,loss]) => <article key={label}><span>{label}</span><strong className={loss ? 'audit-loss' : ''}>{value}</strong><small>{note}</small></article>)}</section>
    <div className="audit-two"><section className="audit-panel"><span className="audit-eyebrow">LEITURA DA AMOSTRA</span><h2>{rows.length ? `${rows.length} resultados para investigar` : 'Sua análise começa com dados'}</h2><p>O histórico descreve esta seleção. Ele não aprova automaticamente uma estratégia para compras.</p><dl className="audit-facts"><div><dt>Resultado médio por contrato</dt><dd>{metrics.expectancy == null ? '—' : money(metrics.expectancy)}</dd></div><div><dt>Ganhos / perdas brutas</dt><dd>{money(metrics.grossWin)} / {money(metrics.grossLoss)}</dd></div><div><dt>Primeiro registro</dt><dd>{rows.length ? new Date(tradeTime(rows[0])).toLocaleString('pt-BR') : '—'}</dd></div><div><dt>Último registro</dt><dd>{rows.length ? new Date(tradeTime(rows.at(-1))).toLocaleString('pt-BR') : '—'}</dd></div></dl><p className="audit-caption">Comparações abaixo usam a mesma seleção. Estratégias com quantidades diferentes de contratos não são diretamente equivalentes.</p></section>
    <section className="audit-panel"><span className="audit-eyebrow">CENÁRIO HISTÓRICO</span><h2><SlidersHorizontal size={17} /> Teste de capacidade da banca</h2><p>Reaplica as entradas e resultados registrados, na ordem cronológica. Interrompe antes da primeira entrada sem saldo suficiente.</p><label className="audit-bank">Banca inicial (USD)<input type="number" min="0.01" step="0.01" value={bank} onChange={e => setBank(e.target.value)} /></label>{!replay ? <p role="alert">Informe uma banca positiva e finita.</p> : !rows.length ? <p className="audit-empty">Selecione um histórico para testar a banca.</p> : <><div className="audit-bank-result"><strong>{money(replay.balance)}</strong><span>{replay.processed} de {rows.length} entradas reproduzidas</span></div><p className={replay.stopped ? 'audit-loss' : 'audit-gain'}>{replay.stopped ? 'Sequência interrompida por saldo insuficiente.' : 'A banca comportou a sequência registrada.'}</p><p>Queda máxima: {money(replay.drawdown)} · {pct(replay.drawdownPct)} do pico correspondente.</p></>}<p className="audit-caption">Cenário sequencial com stakes originais. Não reproduz exposição simultânea, mudanças de payout ou execução real. Não altera a banca nem as configurações dos robôs.</p></section></div>
    <div className="audit-two"><Breakdown title="Comparação por estratégia" rows={auditGroups(rows, strategyName)} /><Breakdown title="Comparação por ativo" rows={auditGroups(rows, t => t.symbol || 'Não informado')} /></div>
    <section className="audit-panel"><div className="audit-section-heading"><h2>Registro auditável</h2><span>Últimos 100 da seleção · CSV inclui todos</span></div><div className="audit-table"><table><thead><tr><th>Data local</th><th>Estratégia</th><th>Ativo</th><th>Entrada</th><th>Resultado</th></tr></thead><tbody>{rows.slice(-100).reverse().map((t,i) => <tr key={t.id || i}><td>{new Date(tradeTime(t)).toLocaleString('pt-BR')}</td><td>{strategyName(t)}</td><td>{t.symbol || '—'}</td><td>{money(t.stake)}</td><td className={t.profit < 0 ? 'audit-loss' : 'audit-gain'}>{money(t.profit)}</td></tr>)}</tbody></table>{!rows.length && <p className="audit-empty">Nenhum resultado válido nesta seleção. Ajuste os filtros ou abra a pesquisa para trabalhar com os dados capturados.</p>}</div><p className="audit-caption">Análise limitada ao histórico carregado da conta. Registros sem data, resultado ou entrada válida são excluídos; contratos com o mesmo identificador são contados uma vez.</p></section>
  </main>;
}
